### ISSUE TITLE
Have a first meeting with the volunteers who will help us for the rythm of the week - Tuesday planning, prep and Thursday backlog

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/Programme#40]

**Comment by MarianaVazquezCYF** [comment]
@Dedekind561 Mitch, once we have all the volunteers, I will create a general call with them to explainhow they can promote their community! However, could you be there as well, to explain the key points of the curriculum that they should do?

**Comment by kfklein15** [comment]
@MarianaVazquezCYF , can you please add details of what this ticket is about? You can edit the top comment and add it there.

**Comment by Dedekind561** [comment]
@MarianaVazquezCYF Following the meeting with trainees, I think this problem is more complex than we first assumed. I think it makes sense to break down this problem further and focus only on _3 parts of the rhythm that are only concerned with trainees. I suggest we focus on **sprint planning**, **preparation** and **starting the backlog**._ 
I suggest that we have

Tuesday - trainees will start **Sprint planning**
Actions on this day:
- Clone backlog issues
- Double-check the issue priority and size. Ensure backlog issues are organised

Tuesday - trainees will start **Preparation**
Actions to start on this day:
- Start reading/watching prep content on the curriculum website
- Practice exercises in the prep view
- Ask questions and discuss concepts in Slack

Thursday - trainees will start "Pick up the backlog"
Actions to start on this day:
- Pick up their first issue to work on from the backlog
- Try figuring out how to complete the issue with support/guidance from the community
- Continue picking up other issues if they complete the first

**Comment by Dedekind561** [comment]
I think getting the trainees to establish the rhythm for those tasks above is a critical first step and reduces the scope of this issue which I think at the moment is too large. I recommend focusing on "code review" in a separate issue. Let's get these three elements working first!

**Comment by Dedekind561** [comment]
Cool

**Comment by Dedekind561** [comment]
Going to close this down @MarianaVazquezCYF as we had the meeting and created further actions 🚀 🔧
