### ISSUE TITLE
CYF+ Products: document challenges per product team

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Programme#42]
### Background
The CYF+ trainees will be allocated within one of the current CYF Tech product teams, with 10h per week to develop features that are aligned to the roadmap of that team. They should work on developing the following [SFIA Levels](https://docs.google.com/document/d/13OM72ZGVWngsWuc5-SFkbHlqBPNhc-79S-SVFFqZZMM/edit#heading=h.8d5ql2cb5tb7).

### Acceptance criteria
- Create a document comparing the challenges for the 3 teams: Dashboard, Rainbird and Class Planner
- Share with stakeholders
- Approve teams

### Owner
@kfklein15

### Stakeholder
POs and Tech Leads of the Product teams, @CodeYourFuture/programme-managers 

### Approver
@SallyMcGrath

**Comment by kfklein15** [comment]
@SallyMcGrath, have you managed to take a look at this doc by any chance? Thank you.

**Comment by SallyMcGrath** [comment]
I had not seen it. Thanks for pinging again.

**Comment by SallyMcGrath** [comment]
@gbencci tagging you here

**Comment by kfklein15** [comment]
Thanks, @SallyMcGrath . Did you see my comment asking to clarify my understanding? Copying it below.
Just to confirm my understanding, 
- 1 person will be on dashboard
- 1 person will rotate between the other two products

**Comment by SallyMcGrath** [comment]
Oh, no I didn't see that.

The google docs sometimes get eaten. I think it's because I still own all those student docs.

I think I forgot one person was on dashboard. We think one person on dashboard, one on classplanner, then rotate them both onto Rainbird for sprints 4 and 5. 

Realistically, they won't get much done on the product in the last two sprints.

**Comment by kfklein15** [comment]
Thanks, @SallyMcGrath!
